# Generated by Django 5.1.2 on 2025-02-16 23:39

import django.db.models.deletion
import file_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=file_manager.models.employee_directory_path, verbose_name='Arquivo')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.employee', verbose_name='Funcionário')),
                ('name_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_manager.namefile', verbose_name='Nome do arquivo')),
            ],
        ),
    ]
