# Generated by Django 5.1.2 on 2025-02-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('file_manager', '0002_remove_file_employee_remove_file_name_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='namefile',
            options={'verbose_name': 'Nome do arquivo', 'verbose_name_plural': 'Nomes dos arquivos'},
        ),
        migrations.AddField(
            model_name='file',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.employee', verbose_name='Funcionário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='name_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_manager.namefile', verbose_name='Nome do arquivo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FileEmployee',
        ),
    ]
