# Generated by Django 5.1.2 on 2024-11-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código CBO')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'CBO',
                'verbose_name_plural': 'CBOs',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Ocupação')),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='cbos.cbo')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sinônimo')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='cbos.occupation')),
            ],
            options={
                'verbose_name': 'Sinônimo',
                'verbose_name_plural': 'Sinônimos',
            },
        ),
    ]
