# Generated by Django 5.1.2 on 2024-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbo',
            name='occupation',
            field=models.CharField(max_length=200, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da Ocupação'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sinônimo'),
        ),
    ]
