# Generated by Django 5.1.2 on 2024-11-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioninfo',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
    ]
