# Generated by Django 5.1.2 on 2024-11-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_admissioninfo_dismissal_date'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninfo',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_info', to='employees.employee', verbose_name='Funcionário'),
        ),
    ]
