# Generated by Django 5.1.2 on 2025-02-16 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('overdue', 'Atrasado'), ('in_progress', 'Em Andamento')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('advance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Adiantamento')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Desconto')),
                ('discount_observation', models.TextField(blank=True, null=True, verbose_name='Observação do desconto')),
                ('first_payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Primeiro Pagamento Parcial')),
                ('first_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Primeiro Pagamento Parcial')),
                ('second_payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Segundo Pagamento Parcial')),
                ('second_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Segundo Pagamento Parcial')),
                ('third_payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Terceiro Pagamento Parcial')),
                ('third_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Terceiro Pagamento Parcial')),
                ('fourth_payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Quarto Pagamento Parcial')),
                ('fourth_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Quarto Pagamento Parcial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bond.admissioninfo', verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['status'], name='payroll_pay_status_daa1bd_idx'), models.Index(fields=['due_date'], name='payroll_pay_due_dat_800aa8_idx')],
            },
        ),
    ]
