# Generated by Django 5.1.2 on 2024-11-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payment_advance_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Primeiro Pagamento Parcial'),
        ),
        migrations.AddField(
            model_name='payment',
            name='first_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Primeiro Pagamento Parcial'),
        ),
        migrations.AddField(
            model_name='payment',
            name='second_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Segundo Pagamento Parcial'),
        ),
        migrations.AddField(
            model_name='payment',
            name='second_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Segundo Pagamento Parcial'),
        ),
    ]
