# Generated by Django 5.1.2 on 2024-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payment_first_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fourth_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Quarto Pagamento Parcial'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fourth_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Quarto Pagamento Parcial'),
        ),
        migrations.AddField(
            model_name='payment',
            name='third_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Terceiro Pagamento Parcial'),
        ),
        migrations.AddField(
            model_name='payment',
            name='third_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Terceiro Pagamento Parcial'),
        ),
    ]
