# Generated by Django 5.1.2 on 2024-11-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payment_discount_payment_discount_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
    ]
